name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is this needed?
      placeholder: Describe the problem or motivation...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the app would this affect?
      options:
        - Map / Routes
        - AI Chat
        - Trip Management
        - Destinations
        - Accommodations
        - POIs / Itinerary
        - Budget
        - Documents
        - Authentication
        - Settings
        - Other
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Essential (can't use the app without it)
        - Important (would significantly improve experience)
        - Nice to have (quality of life improvement)
        - Minor (small enhancement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
      placeholder: Describe alternatives...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups.
      placeholder: Any additional context...
    validations:
      required: false
